spring:
  application:
    name: Auth-Service        
  //config:
    //import: optional:configserver:http://localhost:2222/
    
    spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    username: ashokit
    password: AshokIT@123
    url: jdbc:mysql://localhost:3306/ashokit_ecomm

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
 port: 8081

# Application messages goes here
auth-service:
 messages: 
  userReg: User Created
  userRegErr: User Creation Failed
  login: Login Success
  loginErr: Invalid Credentials  